import { StyleSheet } from "react-native";
import theme from "../theme";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "rgba(239,240,242,1)",
    width: "100%",
    // height: "100%",
  },
  bottom: {
    width: "100%",
    height: 100,
  },
  space: {
    width: "100%",
    height: 100,
  },
  images__address: {
    height: 149,
    flexDirection: "row",
    marginTop: 10,
    marginBottom: 25,
  },
  icon_address_flatlist: {
    width: "100%",
    height: "100%",
  },
  images__address__imageStyle: {
    width: 94,
    height: 149,
    borderRadius: 13,
    overflow: "hidden",
    marginHorizontal: 6,
  },

  images__address__cover: {
    width: 94,
    height: 149,
    backgroundColor: "rgba(68,68,68,0.38)",
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  images__address__name: {
    marginHorizontal: 10,
    marginBottom: 5,
    fontFamily: theme.FontMain,
    color: "rgba(255,255,255,1)",
  },

  image: {
    top: 0,
    left: 0,
    width: "100%",
    height: 201,
    position: "absolute",
  },
  boxSearch: {
    top: 173,
    width: "100%",
    height: 163,
    justifyContent: "center",
    alignItems: "center",
  },
  boxSearch_content: {
    width: "85%",
    height: 163,
    position: "absolute",
    backgroundColor: "rgba(255,255,255,1)",
    borderRadius: 13,
    shadowColor: "rgba(192,189,189,1)",
    shadowOffset: {
      height: 2,
      width: 0,
    },
    elevation: 30,
    shadowOpacity: 0.46,
    shadowRadius: 10,
    overflow: "visible",
    justifyContent: "center",
    alignItems: "center",
  },
  boxSearch_content_input: {
    width: "90%",
    height: 27,
    backgroundColor: "rgba(246,247,249,1)",
    borderRadius: 5,
    flexDirection: "row",
    marginTop: 18,
  },
  boxSearch_content_input_address: {
    width: 46,
    height: 27,
    backgroundColor: "rgba(239,239,239,1)",
    borderRadius: 5,
    flexDirection: "row",
  },
  icon_address: {
    color: "rgba(8,149,253,1)",
    fontSize: 10,
    height: 10,
    width: 10,
    marginTop: 3,
  },
  boxSearch_content_input_address_name: {
    fontFamily: theme.FontMain,
    color: "rgba(8,149,253,1)",
    fontSize: 11,
  },
  iconRow: {
    height: 15,
    flexDirection: "row",
    flex: 1,
    marginRight: 7,
    marginLeft: 4,
    marginTop: 6,
  },
  boxSearch_content_input_content: {
    fontFamily: theme.FontMain,
    color: "rgba(117,117,117,1)",
    fontSize: 10,
    marginLeft: 14,
  },
  boxSearch_content_input_row: {
    height: 27,
    flexDirection: "row",
    flex: 1,
    marginRight: 42,
  },
  boxSearch_content_functions: {
    width: "100%",
    height: 105,
    backgroundColor: "rgba(246,247,249,1)",
    borderBottomRightRadius: 13,
    borderBottomLeftRadius: 13,
    marginTop: 13,
    alignItems: "center",
  },
  icon: {
    position: "absolute",
    color: "rgba(246,247,249,1)",
    fontSize: 35,
  },
  boxSearch_content_function_icon3: {
    width: 50,
    height: 50,
    backgroundColor: "rgba(246,221,59,1)",
    borderRadius: 15,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  boxSearch_content_function_icon1: {
    width: 50,
    height: 50,
    borderRadius: 15,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  boxSearch_content_function_icon2: {
    width: 50,
    height: 50,
    backgroundColor: "rgba(246,221,59,1)",
    borderRadius: 15,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  boxSearch_content_function_row: {
    height: 50,
    flexDirection: "row",
    marginTop: 15,
    width: "90%",
    justifyContent: "space-around",
  },
  boxSearch_content_function: {
    width: "33.3%",
    height: "100%",
    alignItems: "center",
  },
  boxSearch_content_function_title: {
    width: "80%",
    fontFamily: theme.FontMain,
    color: "rgba(117,117,117,1)",
    fontSize: 10,
    top: 3,
    textAlign: "center",
  },
  boxSearch_content_function_title1: {
    width: "80%",
    fontFamily: theme.FontMain,
    color: "rgb(204, 0, 102)",
    fontSize: 10,
    top: 3,
    textAlign: "center",
  },
  boxSearch_function: {
    height: 27,
    width: "100%",
    flexDirection: "row",
    marginTop: 3,
    backgroundColor: "red",
  },
  imageStack: {
    width: "100%",
    height: 336,
  },

  text: {
    fontFamily: theme.FontMain,
    color: "rgba(81,80,80,1)",
    fontSize: 18,
    marginTop: 20,
    marginLeft: 28,
  },
  room_hot: {
    height: 400,
    paddingTop: 12,
    backgroundColor: "rgba(255,255,255,1)",
    borderRadius: 13,
    shadowColor: "rgba(192,189,189,1)",
    shadowOffset: {
      height: 2,
      width: 0,
    },
  },
  icon_room_hot: {
    color: "rgb(0, 153, 255)",
    fontSize: 18,
  },
  room_hot_content: {
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(255,255,255,1)",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 13,
    shadowColor: "rgba(192,189,189,1)",
    shadowOffset: {
      height: 2,
      width: 0,
    },
  },
  room_hot_content_items: {
    marginHorizontal: 10,
    padding: 15,
    borderRadius: 13,
    backgroundColor: theme.PRIMARY_BG_COLOR,
    elevation: 5,
  },
  room_hot_content_item: {
    top: 30,
    height: "90%",
  },
  room_hot_flatlist: {
    width: "100%",
    marginTop: 20,
  },
  room_hot_content_item_image: {
    width: "100%",
    height: "55%",
  },
  text_bottom: {
    width: "90%",
    paddingVertical: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  images__room__hot__imageStyle: {
    width: "100%",
    height: "100%",
    borderRadius: 10,
    overflow: "hidden",
  },
  room_hot_content_item_title: {
    width: "100%",
    height: "45%",
    paddingTop: 5,
  },
  room_hot_content_item_title_category: {
    width: "100%",
    height: "15%",
    left: 10,
  },
  room_hot_content_item_title_category_text: {
    color: theme.PRIMARY_BG_WHITE,
    fontSize: 12,
    fontFamily: theme.FontMain,
  },
  room_hot_content_item_title_name: {
    width: "100%",
    height: "30%",
    left: 10,
    paddingBottom: 3,
  },
  room_hot_content_item_title_name_text: {
    color: theme.PRIMARY_BG_WHITE,
    fontFamily: theme.FontMain,
    fontSize: 18,
    fontWeight: "bold",
  },
  room_hot_content_item_title_price: {
    width: "100%",
    height: "15%",
    left: 18,
  },
  room_hot_content_item_title_price_text: {
    color: "rgba(8,149,253,1)",
    fontFamily: theme.FontMain,
    fontSize: 13,
  },
  room_hot_content_item_title_address: {
    width: "100%",
    height: "30%",
    left: 10,
  },
  room_hot_content_item_title_address_text: {
    color: theme.PRIMARY_BG_DARK,
    fontSize: 12,
    fontFamily: theme.FontMain,
  },
  icon2: {
    paddingTop: 10,
    paddingLeft: 10,
    top: 0,
    left: 0,
    position: "absolute",
    color: "rgba(255,255,255,1)",
    fontSize: 22,
  },
  icon1: {
    paddingTop: 10,
    paddingLeft: 10,
    top: 2,
    left: 2,
    position: "absolute",
    color: "rgb(0, 153, 255)",
    fontSize: 18,
  },
  icon11: {
    paddingTop: 10,
    paddingLeft: 10,
    top: 2,
    left: 2,
    position: "absolute",
    color: "rgb(255, 102, 153)",
    fontSize: 18,
  },
  room_accreditation: {
    width: "100%",
    backgroundColor: "rgb(255,255,255)",
  },
  icon_room_accreditation: {
    color: "rgb(255, 102, 153)",
    fontSize: 18,
  },
  room_accreditation_content: {
    width: "100%",
  },
  room_accreditation_content_item: {
    height: 300,
  },
  room_accreditation_footer: {
    width: "100%",
    height: 40,
    alignItems: "center",
  },

  room_accreditation_flatlist: {
    width: "100%",
    marginTop: 20,
  },
  room_accreditation_content_item_image: {
    width: "100%",
    height: "45%",
  },
  images__room__accreditation__imageStyle: {
    width: "100%",
    height: "100%",
    borderRadius: 10,
    overflow: "hidden",
  },
  room_accreditation_content_item_title: {
    width: "100%",
    height: "55%",
  },
  room_accreditation_content_item_title_category: {
    width: "100%",
    height: "15%",
    left: 10,
  },
  room_accreditation_content_item_title_category_text: {
    color: theme.PRIMARY_BG_DARK,
    fontSize: 12,
    fontFamily: theme.FontMain,
  },
  room_accreditation_content_item_title_name: {
    width: "100%",
    height: "30%",
    left: 10,
    paddingBottom: 3,
  },
  room_accreditation_content_item_title_name_text: {
    color: "black",
    fontSize: 13,
    fontWeight: "bold",
  },
  room_accreditation_content_item_title_price: {
    width: "100%",
    height: "15%",
    left: 15,
  },
  room_accreditation_content_item_title_price_text: {
    color: "rgb(255, 102, 153)",
    fontSize: 12,
    fontFamily: theme.FontMain,
  },
  room_accreditation_content_item_title_address: {
    width: "100%",
    height: "30%",
    left: 10,
  },
  room_accreditation_content_item_title_address_text: {
    color: theme.PRIMARY_BG_DARK,
    fontSize: 12,
    fontFamily: theme.FontMain,
  },
  upperHeader: {
    height: 50,
    backgroundColor: "red",
  },
});

export default styles;
