import "./home.css"

export default function Home() {
    return(
        <div className="home">
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
            Home<br/>
        </div>
    )
}