const houses = [
  {
    id: "1",
    title: "Phòng họp, tổ chức sinh nhật",
    location: "50/14 Trương Văn Thành, p.Hiệp Phú, tp.Thủ Đức",
    image: require("../../assets/house1.jpg"),
    details: `Sạch sẽ, thoáng mát, gần các cửa hàng tập hóa`,
    interiors: [
      require("../../assets/house1.jpg"),
      require("../../assets/interior1.jpg"),
      require("../../assets/interior2.jpg"),
      require("../../assets/interior3.jpg"),
    ],
  },
  {
    id: "2",
    title: "Phòng livestream, phòng hát",
    location: "50/14 Trương Văn Thành, p.Hiệp Phú, tp.Thủ Đức",
    image: require("../../assets/house2.jpg"),
    details: `Sạch sẽ, thoáng mát, gần các cửa hàng tập hóa`,
    interiors: [
      require("../../assets/house2.jpg"),
      require("../../assets/interior1.jpg"),
      require("../../assets/interior2.jpg"),
      require("../../assets/interior3.jpg"),
    ],
  },
  {
    id: "3",
    title: "Phòng làm việc, phòng nghỉ",
    location: "50/14 Trương Văn Thành, p.Hiệp Phú, tp.Thủ Đức",
    image: require("../../assets/house3.jpg"),
    details: `Yên tĩnh, sạch sẽ, thơm`,
    interiors: [
      require("../../assets/house3.jpg"),
      require("../../assets/interior1.jpg"),
      require("../../assets/interior2.jpg"),
      require("../../assets/interior3.jpg"),
    ],
  },
  {
    id: "4",
    title: "Phòng họp, tổ chức sinh nhật",
    location: "50/14 Trương Văn Thành, p.Hiệp Phú, tp.Thủ Đức",
    image: require("../../assets/house1.jpg"),
    details: `Sạch sẽ, thoáng mát, gần các cửa hàng tập hóa`,
    interiors: [
      require("../../assets/house1.jpg"),
      require("../../assets/interior1.jpg"),
      require("../../assets/interior2.jpg"),
      require("../../assets/interior3.jpg"),
    ],
  },
  {
    id: "5",
    title: "Phòng livestream, phòng hát",
    location: "50/14 Trương Văn Thành, p.Hiệp Phú, tp.Thủ Đức",
    image: require("../../assets/house2.jpg"),
    details: `Sạch sẽ, thoáng mát, gần các cửa hàng tập hóa`,
    interiors: [
      require("../../assets/house2.jpg"),
      require("../../assets/interior1.jpg"),
      require("../../assets/interior2.jpg"),
      require("../../assets/interior3.jpg"),
    ],
  },
  {
    id: "6",
    title: "Phòng làm việc, phòng nghỉ",
    location: "50/14 Trương Văn Thành, p.Hiệp Phú, tp.Thủ Đức",
    image: require("../../assets/house3.jpg"),
    details: `Yên tĩnh, sạch sẽ, thơm`,
    interiors: [
      require("../../assets/house3.jpg"),
      require("../../assets/interior1.jpg"),
      require("../../assets/interior2.jpg"),
      require("../../assets/interior3.jpg"),
    ],
  },
  {
    id: "7",
    title: "Phòng họp, tổ chức sinh nhật",
    location: "50/14 Trương Văn Thành, p.Hiệp Phú, tp.Thủ Đức",
    image: require("../../assets/house1.jpg"),
    details: `Sạch sẽ, thoáng mát, gần các cửa hàng tập hóa`,
    interiors: [
      require("../../assets/house1.jpg"),
      require("../../assets/interior1.jpg"),
      require("../../assets/interior2.jpg"),
      require("../../assets/interior3.jpg"),
    ],
  },
  {
    id: "8",
    title: "Phòng livestream, phòng hát",
    location: "50/14 Trương Văn Thành, p.Hiệp Phú, tp.Thủ Đức",
    image: require("../../assets/house2.jpg"),
    details: `Sạch sẽ, thoáng mát, gần các cửa hàng tập hóa`,
    interiors: [
      require("../../assets/house2.jpg"),
      require("../../assets/interior1.jpg"),
      require("../../assets/interior2.jpg"),
      require("../../assets/interior3.jpg"),
    ],
  },
  {
    id: "9",
    title: "Phòng làm việc, phòng nghỉ",
    location: "50/14 Trương Văn Thành, p.Hiệp Phú, tp.Thủ Đức",
    image: require("../../assets/house3.jpg"),
    details: `Yên tĩnh, sạch sẽ, thơm`,
    interiors: [
      require("../../assets/house3.jpg"),
      require("../../assets/interior1.jpg"),
      require("../../assets/interior2.jpg"),
      require("../../assets/interior3.jpg"),
    ],
  },
];

export default houses;
