export default {
  PRIMARY_BG_COLOR: "#37a4f2",
  PRIMARY_COLOR: "#fff",
  PRIMARY_BORDER_COLOR: "#0d47a1",
  PRIMARY_BORDER_WIDTH: 1,

  SECONDARY_BG_COLOR: "#fff",
  SECONDARY_COLOR: "#0d47a1",
  SECONDARY_BORDER_COLOR: "#0d47a1",
  SECONDARY_BORDER_WIDTH: 1,

  CIRCLE_BG_COLOR: "#0d47a1",
  CIRCLE_COLOR: "#fff",
  CIRCLE_HEIGHT: 40,
  CIRCLE_WIDTH: 40,
  CIRCLE_FONT_SIZE: 25,
  CIRCLE_FONT_WEIGHT: "bold",

  ALIGN_ITEMS: "center",
  JUSTIFY_CONTENT: "center",
  PADDING_SIZE: 10,
  WIDTH: 150,
  BORDER_RADIUS: 30,
  MARGIN_HORIZONTAL: 2,

  TEXT_ALIGN: "center",
  FONT_SIZE: 18,
};
